--changeset vladislav:1

create table book(
     id int generated by default as identity primary key,
     name varchar(100) not null,
     author varchar(100) not null,
     year int check ( year > 0 ),
    count int check ( count > 0 ),
    views int,
    description varchar,
    url varchar
)