--changeset vladislav:1

create table order_book(
   id int generated by default as identity primary key,
   person_id int references person(id) on delete cascade ,
   book_id int references book(id) on delete cascade ,
   order_date date,
   status varchar,
   unique (person_id, book_id)
)